const worldOptions = [
    { value: 'North America', label: 'North America', isDisabled: true },
    { value: 'Aether', label: 'Aether', isDisabled: true },
    { value: 'Adamantoise', label: 'Adamantoise' },
    { value: 'Cactuar', label: 'Cactuar' },
    { value: 'Faerie', label: 'Faerie' },
    { value: 'Gilgamesh', label: 'Gilgamesh' },
    { value: 'Jenova', label: 'Jenova' },
    { value: 'Midgardsormr', label: 'Midgardsormr' },
    { value: 'Sargantanas', label: 'Sargantanas' },
    { value: 'Siren', label: 'Siren' },
    { value: 'Crystal', label: 'Crystal', isDisabled: true },
    { value: 'Balmung', label: 'Balmung' },
    { value: 'Brynhildr', label: 'Brynhildr' },
    { value: 'Coeurl', label: 'Coeurl' },
    { value: 'Diabolos', label: 'Diabolos' },
    { value: 'Goblin', label: 'Goblin' },
    { value: 'Malboro', label: 'Malboro' },
    { value: 'Mateus', label: 'Mateus' },
    { value: 'Zalera', label: 'Zalera' },
    { value: 'Dynamis', label: 'Dynamis', isDisabled: true },
    { value: 'Cuchulainn', label: 'Cuchulainn' },
    { value: 'Golem', label: 'Golem' },
    { value: 'Halicarnassus', label: 'Halicarnassus' },
    { value: 'Kraken', label: 'Kraken' },
    { value: 'Maduin', label: 'Maduin' },
    { value: 'Marilith', label: 'Marilith' },
    { value: 'Rafflesia', label: 'Rafflesia' },
    { value: 'Seraph', label: 'Seraph' },
    { value: 'Primal', label: 'Primal', isDisabled: true },
    { value: 'Behemoth', label: 'Behemoth' },
    { value: 'Excalibur', label: 'Excalibur' },
    { value: 'Exodus', label: 'Exodus' },
    { value: 'Famfrit', label: 'Famfrit' },
    { value: 'Hyperion', label: 'Hyperion' },
    { value: 'Lamia', label: 'Lamia' },
    { value: 'Leviathan', label: 'Leviathan' },
    { value: 'Ultros', label: 'Ultros' },
    { value: 'Europe', label: 'Europe', isDisabled: true },
    { value: 'Chaos', label: 'Chaos', isDisabled: true },
    { value: 'Cerberus', label: 'Cerberus' },
    { value: 'Louisoix', label: 'Louisoix' },
    { value: 'Moogle', label: 'Moogle' },
    { value: 'Omega', label: 'Omega' },
    { value: 'Phantom', label: 'Phantom' },
    { value: 'Ragnarok', label: 'Ragnarok' },
    { value: 'Sagittarius', label: 'Sagittarius' },
    { value: 'Spriggan', label: 'Spriggan' },
    { value: 'Light', label: 'Light', isDisabled: true },
    { value: 'Alpha', label: 'Alpha' },
    { value: 'Lich', label: 'Lich' },
    { value: 'Odin', label: 'Odin' },
    { value: 'Phoenix', label: 'Phoenix' },
    { value: 'Raiden', label: 'Raiden' },
    { value: 'Shiva', label: 'Shiva' },
    { value: 'Twintania', label: 'Twintania' },
    { value: 'Zodiark', label: 'Zodiark' },
    { value: 'Oceania', label: 'Oceania', isDisabled: true },
    { value: 'Materia', label: 'Materia', isDisabled: true },
    { value: 'Bismarck', label: 'Bismarck' },
    { value: 'Ravana', label: 'Ravana' },
    { value: 'Sephirot', label: 'Sephirot' },
    { value: 'Sophia', label: 'Sophia' },
    { value: 'Zurvan', label: 'Zurvan' },
    { value: 'Japan', label: 'Japan', isDisabled: true },
    { value: 'Elemental', label: 'Elemental', isDisabled: true },
    { value: 'Aegis', label: 'Aegis' },
    { value: 'Atomos', label: 'Atomos' },
    { value: 'Carbuncle', label: 'Carbuncle' },
    { value: 'Garuda', label: 'Garuda' },
    { value: 'Gungnir', label: 'Gungnir' },
    { value: 'Kujata', label: 'Kujata' },
    { value: 'Tonberry', label: 'Tonberry' },
    { value: 'Typhon', label: 'Typhon' },
    { value: 'Gaia', label: 'Gaia', isDisabled: true },
    { value: 'Alexander', label: 'Alexander' },
    { value: 'Bahamut', label: 'Bahamut' },
    { value: 'Durandal', label: 'Durandal' },
    { value: 'Fenrir', label: 'Fenrir' },
    { value: 'Ifrit', label: 'Ifrit' },
    { value: 'Ridill', label: 'Ridill' },
    { value: 'Tiamat', label: 'Tiamat' },
    { value: 'Ultima', label: 'Ultima' },
    { value: 'Mana', label: 'Mana', isDisabled: true },
    { value: 'Anima', label: 'Anima' },
    { value: 'Asura', label: 'Asura' },
    { value: 'Chocobo', label: 'Chocobo' },
    { value: 'Hades', label: 'Hades' },
    { value: 'Ixion', label: 'Ixion' },
    { value: 'Masamune', label: 'Masamune' },
    { value: 'Pandaemonium', label: 'Pandaemonium' },
    { value: 'Titan', label: 'Titan' },
    { value: 'Meteor', label: 'Meteor', isDisabled: true },
    { value: 'Belias', label: 'Belias' },
    { value: 'Mandragora', label: 'Mandragora' },
    { value: 'Ramuh', label: 'Ramuh' },
    { value: 'Shinryu', label: 'Shinryu' },
    { value: 'Unicorn', label: 'Unicorn' },
    { value: 'Valefor', label: 'Valefor' },
    { value: 'Yojimbo', label: 'Yojimbo' },
    { value: 'Zeromus', label: 'Zeromus' },
];

export default worldOptions;